# Generated by Django 3.1 on 2020-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdate', models.DateField()),
                ('weight', models.FloatField(max_length=100)),
                ('steps', models.IntegerField()),
                ('exercise', models.CharField(choices=[('N/A', 'Exercise'), ('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('notes', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
